/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memcard/me/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the authenticated player's state
         * @description Returns the current state object and its ETag. Supply `If-None-Match` with a previously received ETag for cache validation; a match yields `304 Not Modified`. A player with no stored state receives an empty state body and the sentinel ETag.
         */
        get: operations["getMemcardState"];
        /**
         * Save the authenticated player's state
         * @description Writes the supplied state using a conditional write. The client must send the ETag from its most recent fetch in `If-Match`; new players send the sentinel ETag. A stale ETag yields `409 Conflict`.
         */
        put: operations["putMemcardState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthCheck: {
            /** @example ok */
            status: string;
            /** Format: date-time */
            timestamp: string;
            /** @example memcard */
            service: string;
        };
        MemcardStateResponse: {
            /** Format: date-time */
            lastModified?: string;
            state: {
                [key: string]: unknown;
            };
        };
        MemcardStateUpdate: {
            state: {
                [key: string]: unknown;
            };
        };
        MemcardSaveResponse: {
            /** @example true */
            success: boolean;
        };
        StateConflict: {
            /** @example STATE_CONFLICT */
            errorCode: string;
            currentEtag: string;
        };
        Error: {
            message: string;
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    getMemcardState: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag of the cached version held by the client. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state returned */
            200: {
                headers: {
                    /** @description Opaque version identifier of the returned state */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemcardStateResponse"];
                };
            };
            /** @description Client's cached state is current; no body returned */
            304: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, expired, or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description S3 unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putMemcardState: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag the client believes is current (or the sentinel for a first write). */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemcardStateUpdate"];
            };
        };
        responses: {
            /** @description State saved */
            200: {
                headers: {
                    /** @description Newly issued opaque version identifier */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemcardSaveResponse"];
                };
            };
            /** @description Malformed request body or missing required header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing, expired, or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description State was modified since the client's last fetch */
            409: {
                headers: {
                    /** @description Current opaque version identifier the client should reconcile against */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateConflict"];
                };
            };
            /** @description Request body exceeds the configured size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description S3 unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
